project_name: partman

# GoReleaser configuration file version
version: 2

dist: .builds

before:
  hooks:
    - go mod tidy

builds:
  - main: ./
    binary: partman
    ldflags:
      - -s -w -X github.com/phcreery/partman.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm

release:
  disable: true
  draft: true

archives:
  - formats: ["zip"]
    files:
      - LICENSE*
      - CHANGELOG*

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^dist-ui:"
