FROM linuxcontainers/debian-slim:latest
COPY ./.builds/partman_*_linux_amd64.zip /partman.zip
RUN apt-get update && \
    apt-get install -y unzip && \
    rm -rf /var/lib/apt/lists/*
RUN unzip /partman.zip -d /partman && \
    rm /partman.zip && \
    chmod +x /partman/partman
COPY ./pb_data /partman/pb_data

EXPOSE 8091
RUN /partman/partman migrate up
CMD ["/partman/partman", "serve", "--http=0.0.0.0:8091"]